Repository mdx-js/mdx, pull requests merged in 2019-12, with the labels that each got.

#811 feat: add typescript typings for @mdx-js/mdx, @mdx-js/react, @mdx-js/runtime, and @mdx-js/vue
  docs/advanced/typescript.mdx
  packages/loader/package.json
  packages/loader/types/index.d.ts
  packages/loader/types/tsconfig.json
  packages/loader/types/tslint.json
  packages/mdx/package.json
  packages/mdx/types/index.d.ts
  packages/mdx/types/mdx-test.ts
  packages/mdx/types/tsconfig.json
  packages/mdx/types/tslint.json
  packages/react/package.json
  packages/react/types/index.d.ts
  packages/react/types/mdx-react-test.tsx
  packages/react/types/tsconfig.json
  packages/react/types/tslint.json
  packages/runtime/package.json
  packages/runtime/types/index.d.ts
  packages/runtime/types/mdx-runtime-test.tsx
  packages/runtime/types/tsconfig.json
  packages/runtime/types/tslint.json
  packages/vue-loader/package.json
  packages/vue-loader/types/index.d.ts
  packages/vue-loader/types/tsconfig.json
  packages/vue-loader/types/tslint.json
  packages/vue/package.json
  packages/vue/types/index.d.ts
  packages/vue/types/mdx-vue-test.ts
  packages/vue/types/tsconfig.json
  packages/vue/types/tslint.json
  yarn.lock
Labels: ☂️ area/types, 💎 v2, 🦋 type/enhancement, 🧑 semver/major, 🧘 status/waiting

#877 fix: runtime should be bundled and considered as node pkg - fix #876
  package.json
  packages/runtime/package.json
  yarn.lock
Labels: 🐛 type/bug

#886 chore: update razzle in examples
  examples/razzle/package.json
  examples/razzle/yarn.lock
Labels: 📚 area/docs, 📦 area/deps
