Repository mdx-js/mdx, pull requests merged in 2020-12, with the labels that each got.

#1233 Add types to `@mdx-js/preact`
  docs/advanced/typescript.mdx
  packages/preact/package.json
  packages/preact/types/index.d.ts
  packages/preact/types/mdx-preact-test.tsx
  packages/preact/types/tsconfig.json
  packages/preact/types/tslint.json
Labels: ☂️ area/types, 💎 v2, 🦋 type/enhancement, 🧑 semver/major

#1381 Update `mdast-util-to-hast`
  packages/mdx/mdx-ast-to-mdx-hast.js
  packages/mdx/package.json
  yarn.lock
Labels: 📦 area/deps

#1382 Refactor to generate JS AST
  packages/babel-plugin-apply-mdx-type-props/index.js
  packages/babel-plugin-apply-mdx-type-props/test/index.test.js
  packages/mdx/index.js
  packages/mdx/mdx-hast-to-jsx.js
  packages/mdx/package.json
  packages/mdx/test/index.test.js
  packages/preact/test/test.js
  packages/react/test/test.js
  packages/remark-mdx/package.json
  packages/remark-mdx/test/fixtures/block-parsing.json
  packages/remark-mdx/test/fixtures/character-reference.json
  packages/remark-mdx/test/fixtures/examples-from-jsx.json
  packages/remark-mdx/test/fixtures/examples-from-react-accessibility.json
  packages/remark-mdx/test/fixtures/examples-from-react-jsx-in-depth.json
  packages/remark-mdx/test/fixtures/expressions.json
  packages/remark-mdx/test/fixtures/format-attributes.json
  packages/remark-mdx/test/fixtures/interleaving.json
  packages/remark-mdx/test/fixtures/markdown.json
  packages/remark-mdx/test/fixtures/span.json
  packages/runtime/test/index.test.js
  packages/vue-loader/package.json
  packages/vue/package.json
  packages/vue/src/create-element.js
  packages/vue/test/test.js
  yarn.lock
Labels: 🗄 area/interface

#1393 Remove code for deprecated packages
  package.json
  packages/babel-plugin-html-attributes-to-jsx/index.js
  packages/babel-plugin-html-attributes-to-jsx/package.json
  packages/babel-plugin-html-attributes-to-jsx/readme.md
  packages/babel-plugin-html-attributes-to-jsx/test/index.test.js
  packages/babel-plugin-html-attributes-to-jsx/translations.js
  packages/remark-mdx-remove-exports/license
  packages/remark-mdx-remove-exports/package.json
  packages/remark-mdx-remove-exports/readme.md
  packages/remark-mdx-remove-imports/license
  packages/remark-mdx-remove-imports/package.json
  packages/remark-mdx-remove-imports/readme.md
  packages/remark-mdxjs/license
  packages/remark-mdxjs/package.json
  packages/remark-mdxjs/readme.md
  packages/test-util/index.js
  packages/test-util/license
  packages/test-util/package.json
  packages/test-util/types/index.d.ts
  packages/test-util/types/mdx-js-test-util-test.tsx
  packages/test-util/types/tsconfig.json
  packages/test-util/types/tslint.json
  packages/util/index.js
  packages/util/license
  packages/util/package.json
  packages/util/readme.md
  packages/util/test/test.js
  packages/util/types/index.d.ts
  packages/util/types/mdx-js-util-test.ts
  packages/util/types/tsconfig.json
  packages/util/types/tslint.json
  yarn.lock
Labels: 🏡 area/internal

#1392 Update dependencies, dev-dependencies
  package.json
  packages/babel-plugin-apply-mdx-type-props/index.js
  packages/babel-plugin-apply-mdx-type-props/package.json
  packages/babel-plugin-extract-export-names/package.json
  packages/babel-plugin-extract-import-names/package.json
  packages/loader/package.json
  packages/loader/test/index.test.js
  packages/mdx/package.json
  packages/remark-mdx/test/index.js
  packages/vue-loader/test/test.js
  yarn.lock
Labels: 📦 area/deps

#1395 Add support for named export default from
  packages/mdx/mdx-hast-to-jsx.js
  packages/mdx/test/index.test.js
Labels: 🗄 area/interface, 🙆 status/confirmed, 🦋 type/enhancement, 🧒 semver/minor

#1397 Remove custom scripts from `remark-mdx`
  .eslintignore
  packages/remark-mdx/.editorconfig
  packages/remark-mdx/.gitignore
  packages/remark-mdx/.prettierignore
  packages/remark-mdx/.remarkignore
  packages/remark-mdx/index.js
  packages/remark-mdx/package.json
  packages/remark-mdx/test/index.js
  yarn.lock
Labels: 🏡 area/internal

#1399 Replace Babel w/ estree
  packages/babel-plugin-apply-mdx-type-props/index.js
  packages/babel-plugin-apply-mdx-type-props/package.json
  packages/babel-plugin-apply-mdx-type-props/readme.md
  packages/babel-plugin-apply-mdx-type-props/test/index.test.js
  packages/babel-plugin-extract-export-names/index.js
  packages/babel-plugin-extract-export-names/package.json
  packages/babel-plugin-extract-export-names/readme.md
  packages/babel-plugin-extract-export-names/test/index.test.js
  packages/babel-plugin-extract-import-names/index.js
  packages/babel-plugin-extract-import-names/package.json
  packages/babel-plugin-extract-import-names/readme.md
  packages/babel-plugin-extract-import-names/test/index.test.js
  packages/mdx/estree-to-js.js
  packages/mdx/mdx-hast-to-jsx.js
  packages/mdx/package.json
  packages/mdx/test/index.test.js
  yarn.lock
Labels: 🏡 area/internal, 👶 semver/patch, 🙆 status/confirmed, 🦋 type/enhancement

#1394 Add `jsxFrag` pragma, use fragment for shortcode warning
  packages/mdx/estree-to-js.js
  packages/mdx/index.js
  packages/mdx/mdx-hast-to-jsx.js
  packages/mdx/test/index.test.js
  packages/preact/package.json
  packages/preact/src/create-element.js
  packages/preact/test/test.js
  packages/react/src/create-element.js
  packages/react/test/test.js
  packages/vue-loader/index.js
  packages/vue/test/test.js
Labels: 🗄 area/interface, 🙆 status/confirmed, 🦋 type/enhancement, 🧒 semver/minor

#1412 Add back build for runtime
  packages/runtime/package.json
Labels: 🐛 type/bug

#1414 Fix sentences running together
  docs/404.mdx
  docs/about.mdx
  docs/advanced/components.mdx
  docs/advanced/transform-content.mdx
  docs/blog/custom-pragma.mdx
  docs/blog/shortcodes.mdx
  docs/blog/v1.mdx
  docs/contributing.mdx
  docs/getting-started/babel-config.mdx
  docs/getting-started/index.mdx
  docs/getting-started/next.mdx
  docs/getting-started/webpack.mdx
  docs/getting-started/x0.mdx
  docs/getting-started/zero.mdx
  docs/guides/custom-loader.mdx
  docs/guides/live-code.mdx
  docs/guides/markdown-in-components.md
  docs/guides/mdx-embed.md
  docs/guides/syntax-highlighting.mdx
  docs/guides/vue.mdx
  docs/guides/wrapper-customization.mdx
  docs/guides/writing-a-plugin.mdx
  docs/migrating/v1.mdx
  docs/support.mdx
Labels: 📚 area/docs

#1415 Update examples, `react`
  docs/advanced/plugins.mdx
  docs/getting-started/next.mdx
  docs/getting-started/webpack.mdx
  docs/guides/custom-loader.mdx
  docs/guides/math-blocks.mdx
  docs/guides/syntax-highlighting.mdx
  docs/guides/vue.mdx
  examples/create-react-app/.babelrc
  examples/create-react-app/package.json
  examples/gatsby/package.json
  examples/next/next.config.js
  examples/next/package.json
  examples/next/pages/_app.js
  examples/next/pages/index.mdx
  examples/parcel/package.json
  examples/razzle/package.json
  examples/razzle/razzle.config.js
  examples/razzle/src/App.js
  examples/razzle/src/example.mdx
  examples/react-static/package.json
  examples/react-static/readme.md
  examples/react-static/static.config.js
  examples/react-web-components/gatsby-config.js
  examples/react-web-components/package.json
  examples/react-web-components/readme.md
  examples/shortcodes/gatsby-config.js
  examples/shortcodes/package.json
  examples/syntax-highlighting/gatsby-config.js
  examples/syntax-highlighting/package.json
  examples/terminal/example.js
  examples/terminal/package.json
  examples/vue-loader/.browserslistrc
  examples/vue-loader/package.json
  examples/vue-loader/readme.md
  examples/vue-loader/src/hello-world.mdx
  examples/vue-loader/vue.config.js
  examples/vue/README.md
  examples/vue/readme.md
  examples/vue/src/App.vue
  examples/vue/src/Box.vue
  examples/vue/src/Content.mdx
  examples/vue/src/components/HelloWorld.vue
  examples/vue/src/test.mdx
  examples/vue/vue.config.js
  examples/webpack/.babelrc
  examples/webpack/package.json
  examples/webpack/webpack.config.js
  package.json
  packages/gatsby-theme-mdx/package.json
  packages/loader/package.json
  packages/parcel-plugin-mdx/package.json
  packages/parcel-plugin-mdx/src/MDXAsset.js
  packages/parcel-plugin-mdx/src/index.js
  packages/parcel-plugin-mdx/test/Content.mdx
  packages/parcel-plugin-mdx/test/index.test.js
  packages/react/package.json
  packages/runtime/package.json
  yarn.lock
Labels: 👩‍⚕ area/health, 👶 semver/patch, 📚 area/docs, 🦋 type/enhancement

#1422 Update CRA guide
  .gitignore
  docs/getting-started/create-react-app.mdx
  docs/getting-started/index.mdx
  examples/create-react-app/.babelrc
  examples/create-react-app/.env
  examples/create-react-app/.gitignore
  examples/create-react-app/package.json
  examples/create-react-app/public/favicon.ico
  examples/create-react-app/public/index.html
  examples/create-react-app/public/manifest.json
  examples/create-react-app/readme.md
  examples/create-react-app/src/App.css
  examples/create-react-app/src/App.js
  examples/create-react-app/src/App.test.js
  examples/create-react-app/src/content.mdx
  examples/create-react-app/src/index.css
  examples/create-react-app/src/index.js
  examples/create-react-app/src/logo.svg
  package.json
  packages/create-mdx/readme.md
  yarn.lock
Labels: 📚 area/docs
