Repository mdx-js/mdx, pull requests merged in 2020-07, with the labels that each got.

#1160 Improve export name extraction for shortcode generation
  package.json
  packages/babel-plugin-extract-export-names/index.js
  packages/babel-plugin-extract-export-names/package.json
  packages/babel-plugin-extract-export-names/readme.md
  packages/babel-plugin-extract-export-names/test/index.test.js
  packages/babel-plugin-extract-import-names/test/index.test.js
  packages/mdx/mdx-hast-to-jsx.js
  packages/mdx/package.json
  packages/remark-mdxjs/test/__snapshots__/test.js.snap
  yarn.lock
Labels: 💎 v2

#1173 Make testing matrix simpler
  .github/workflows/ci.yml
Labels: 💎 v2, 🕸️ area/tests

#1174 Remove deprecated plugin options, fixes #718
  packages/mdx/index.js
Labels: 💎 v2, 🗄 area/interface

#1178 ci(github): update github actions and dtslint to latest
  .github/workflows/ci.yml
  yarn.lock
Labels: 👶 semver/patch, 💎 v2, 🕸️ area/tests

#1180 ci(github): update github actions to latest versions
  .github/workflows/lint.yml
  .github/workflows/publish.yml
Labels: 🏗 area/tools, 👶 semver/patch, 💎 v2

#1181 docs(typescript): document how to use mdx 2 with typescript
  docs/advanced/typescript.mdx
Labels: ☂️ area/types, 💎 v2, 📚 area/docs

#1179 Make type test run in their own action, closes #1172
  .github/workflows/types.yml
  package.json
Labels: ☂️ area/types, 💎 v2, 🕸️ area/tests

#1175 Implement ability to opt out of MDXProvider components
  packages/preact/src/context.js
  packages/preact/test/sandbox-fixture.js
  packages/preact/test/test.js
  packages/react/src/context.js
  packages/react/test/sandbox-fixture.js
  packages/react/test/test.js
  packages/react/types/index.d.ts
  packages/react/types/mdx-react-test.tsx
Labels: ☂️ area/types, 💎 v2, 🗄 area/interface

#1199 Remove layout props in compiled jsx
  packages/mdx/mdx-hast-to-jsx.js
  packages/mdx/test/index.test.js
  packages/remark-mdxjs/test/__snapshots__/test.js.snap
Labels: 💎 v2
