Repository mdx-js/mdx, pull requests merged in 2020-11, with the labels that each got.

#1213 Update typescript.mdx
  docs/advanced/typescript.mdx
Labels: ☂️ area/types, 📚 area/docs

#1343 Fix `delete` -> `del` in docs on typescript
  docs/advanced/typescript.mdx
Labels: ☂️ area/types, 📚 area/docs

#1349 Fix tests on next
  package.json
  packages/babel-plugin-apply-mdx-type-props/package.json
  packages/babel-plugin-extract-export-names/package.json
  packages/babel-plugin-extract-import-names/package.json
  packages/babel-plugin-remove-export-keywords/package.json
  packages/gatsby-theme-mdx/package.json
  packages/gatsby-theme-mdx/src/components/playground-editor.js
  packages/gatsby-theme-mdx/src/components/search.js
  packages/loader/package.json
  packages/mdx/package.json
  packages/mdx/util.js
  packages/react/package.json
  packages/remark-mdx-remove-exports/package.json
  packages/remark-mdx-remove-imports/package.json
  packages/remark-mdx/package.json
  packages/remark-mdx/test/index.js
  packages/remark-mdxjs/package.json
  packages/runtime/package.json
  packages/test-util/package.json
  packages/util/package.json
  packages/vue-loader/package.json
  packages/vue/package.json
  yarn.lock
Labels: 🏗 area/tools, 🐛 type/bug, 🕸️ area/tests, 🙆 status/confirmed

#1350 Refactor and test `remark-mdxjs`
  packages/remark-mdxjs/extract-imports-and-exports.js
  packages/remark-mdxjs/index.js
  packages/remark-mdxjs/test/__snapshots__/import-export.test.js.snap
  packages/remark-mdxjs/test/__snapshots__/test.js.snap
  packages/remark-mdxjs/test/fixtures/import-export.js
  packages/remark-mdxjs/test/fixtures/inline-parsing.js
  packages/remark-mdxjs/test/import-export.test.js
  packages/remark-mdxjs/test/inline-parsing.test.js
  packages/remark-mdxjs/test/test.js
  yarn.lock
Labels: 🕸️ area/tests, 🗄 area/interface

#1347 Refactor `@mdx-js/mdx` to clean code, test 100%
  packages/mdx/.babelrc
  packages/mdx/index.js
  packages/mdx/mdx-ast-to-mdx-hast.js
  packages/mdx/mdx-hast-to-jsx.js
  packages/mdx/package.json
  packages/mdx/test/fixtures/blog-post.mdx
  packages/mdx/test/fixtures/export-with-shortcode.mdx
  packages/mdx/test/fixtures/imports.mdx
  packages/mdx/test/fixtures/ponylang.mdx
  packages/mdx/test/index.test.js
  packages/mdx/test/render.test.js
  packages/mdx/types/index.d.ts
  yarn.lock
Labels: 🏡 area/internal, 💎 v2, 🕸️ area/tests, 🦋 type/enhancement, 🧘 status/waiting
