Repository mdx-js/mdx, pull requests merged in 2023-10, with the labels that each got.

#2360 Update link to KaTeX CSS in docs
  docs/guides/math.mdx
Labels: 📚 area/docs

#2281 react: fix to classify `@types/react` as a peer dependency
  package-lock.json
  packages/react/package.json
Labels: 🐛 type/bug, 📦 area/deps, ☂️ area/types, 👶 semver/patch, 🤞 phase/open

#2376 Add support for Vite development mode
  package-lock.json
  package.json
  packages/rollup/lib/index.js
  packages/rollup/test/index.js
  packages/rollup/test/vite-entry.mdx
Labels: 🦋 type/enhancement, 🗄 area/interface, 🧑 semver/major, 🤞 phase/open

#2377 Add GitHub pages
  .github/workflows/website.yml
Labels: 🕸 area/website, 🤞 phase/open

#2386 loader: fix types
  packages/loader/index.cjs
Labels: 🐛 type/bug, 🗄 area/interface, ☂️ area/types, 👶 semver/patch
